version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  system_packages: false

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

formats:
  - html
