version: 2


build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.cargo/bin:$PATH"
    - uv pip install -e ".[dev]"
    - sphinx-build -b html docs/source _build/html

sphinx:
  configuration: docs/source/conf.py

formats:
  - htmlzip
  - pdf
