site_name: MBOX Converter
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/pamagister/mbox_converter
repo_name: GitHub

theme:
  name: readthedocs
  features:
    - navigation.instant

markdown_extensions:
  - toc:
      permalink: "#"
  - tables
  - admonition


