site_name: MBOX Converter
repo_url: https://github.com/pamagister/mbox_converter

nav:
    - Home: index.md
    - Installation: install.md
    - Command line interface: cli.md
    - Contributing: contributing.md
theme: readthedocs
