name: Setup Environment

description: Setup uv environment

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Create virtual environment
      run: uv venv .venv --python ${{ matrix.python-version }}
      shell: bash

    - name: Activate virtual environment
      run: echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
      shell: bash

    - name: Install dependencies
      run: |
        uv pip install -e .
        uv pip install -e ".[dev]"
      shell: bash
