name: Build macOS App

on:
  push:
    tags:
      - 'v*'  # Trigger for tags like v0.1.3
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Setup Poetry
        uses: ./.github/actions/setup-poetry  # Composite Action

      - name: Check poetry setup
        run: |
          poetry --version

      - name: Install dependencies
        run: poetry install --with dev

      - name: Build macOS Executable with PyInstaller
        run: |
          poetry run pyinstaller --onefile mbox_converter/cli.py --name MboxConverter

      - name: Prepare ZIP file for release
        run: |
          mkdir release
          cp dist/MboxConverter release/
          cp example.mbox release/
          cp README.md release/
          cd release && zip -r ../MboxConverter-macOS.zip *

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: MboxConverter-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
