name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'  # Triggers for tags like v0.1.3
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Setup Environment # Composite Action
        uses: ./.github/actions/setup-environment
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build EXE with PyInstaller
        run: |
          uv run pyinstaller --onefile mbox_converter/cli.py --name MboxConverter

      - name: Prepare ZIP file for release
        run: |
          mkdir release
          copy dist\MboxConverter.exe release\
          copy example.mbox release\
          copy README.md release\
          powershell Compress-Archive -Path release\* -DestinationPath MboxConverter-win.zip

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: MboxConverter-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
