# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linter:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Create virtual environment
        run: uv venv .venv --python ${{ matrix.python-version }}

      - name: Activate virtual environment
        run: echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          uv pip install -e .
          uv pip install -e ".[dev]"

      - name: Run linter
        run: make lint

  tests_linux_macos:
    needs: linter
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Create virtual environment
        run: uv venv .venv --python ${{ matrix.python-version }}

      - name: Activate virtual environment
        run: echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          uv pip install -e .
          uv pip install -e ".[dev]"

      - name: Run tests
        run: make test

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v5

